apiVersion: v1
kind: PersistentVolume
metadata:
  name: pywechatnoreply-nfs-pv
  labels:
    storage: pywechatnoreply-nfs-pv
  annotations:
    kubernetes.io.description: pv-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - vers=4
  nfs:
    path: /home/analysis_group
    server: 10.15.67.2
