kind: Service
apiVersion: v1
metadata:
  name: myservice-pywechatnoreply
  namespace: batchpy
spec:
  selector:
    app: pywechatnoreply
  ports:
    - name: myport
      protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: myservice-pywechatnoreply-ext
  namespace: batchpy
spec:
  selector:
    app: pywechatnoreply
  ports:
    - name: myport
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
