apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy-helloworld
  namespace: batchpy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - image: harbor.my.org:1080/python-app/pywechatnoreply:helloworld
          name: helloworld
          resources:
            limits:
              cpu: "4"
              memory: 12Gi
            requests:
              cpu: 250m
              memory: 750Mi
