apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/helloworld
patchesStrategicMerge:
- deployment_patch.yaml
commonAnnotations:
  manual_redeploy: 2021-06-03-18-18
